modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.seasonsmod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="seasonsmod"
version="1.0.0"
displayName="Seasons and Weather Overhaul"
description='''
Adds four seasons to Minecraft with real gameplay effects.
'''